### ISSUE TITLE
MA0015 doesn't allow lambda parameters for `paramName`

### ISSUE THREAD

**Issue by YoshiRulz** [meziantou/Meziantou.Analyzer#342]
**Context**
Rule identifier: _MA0015_
Target Framework: _.NET Standard 2.0_
Language version: _9.0_

**Describe the bug**
The Analyzer flags the below with `'addr' is not a valid parameter name` though it's correctly referencing one of the lambda parameters. If converted to a local method, there is no warning.

**To Reproduce**
Code or steps to reproduce the behavior:
```csharp
void CreateMemoryDomain(string name, ulong size, Action<ulong, byte> writeCallback) {}
// [...]
CreateMemoryDomain(
	"System Bus",
	0x10000U,
	(addr, value) =>
	{
		if (addr is < 0U or > 0xFFFFU) throw new ArgumentOutOfRangeException(paramName: nameof(addr), addr, message: "address out of range");
		// calls into unmanaged
	});
```

**Additional context**
[actual code](https://github.com/TASEmulators/BizHawk/blob/84886b7395deb595e233a4845eb5c168e5d3eb84/src/BizHawk.Emulation.Cores/Consoles/Nintendo/SameBoy/SameBoy.IMemoryDomains.cs#L46-L64)

**Comment by meziantou** [comment]
Thanks for reporting the issue!
It should be fixed in version `1.0.706`

**Comment by YoshiRulz** [comment]
Thanks for the quick response, but you missed the case where there's only one parameter without parens :P

**Comment by meziantou** [comment]
I was too lazy to test all cases yesterday... I hope the latest version handles all cases

Fixed by c7b2738caddb1015b4c022182c6a57e6fef12fc0
